version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: painless/tox
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: tox
#  export-to-artifactory:
#    docker:
#      - image: <image made to meet company specs on building and exporting>
#    steps:
#      - checkout
#      - run:
#         name: Export to Artifactory
#          command: <command made to build and export to artifactory>


workflows:
  sample:
    jobs:
      - build-and-test
